Add codecov integration
lumigo-io/go-tracer-beta pull request #7
Opened 2021-12-12 21:18 UTC by spirosoik

2022-02-06 16:20 UTC, saartochner requested changes
Great!
added the integration to our services.
Two comments:
1. add this badge to the README:
[![codecov](https://codecov.io/gh/lumigo-io/go-tracer-beta/branch/master/graph/badge.svg?token=x49mnWnhaz)](https://codecov.io/gh/lumigo-io/go-tracer-beta)
2. I think that we need to run the checks on master (you currently skip it in the circleci) - because we always want to compare the current branch to the master :)

2022-02-18 20:30 UTC, spirosoik commented
@nirLumigo this is fixed

2022-02-20 07:53 UTC, saartochner approved these changes

2022-02-20 08:54 UTC, nirLumigo approved these changes

2022-02-24 11:54 UTC, merged